module.exports = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "surface-container-lowest": "#000f21",
                        "surface-dim": "#031427",
                        "on-secondary-container": "#adb4ce",
                        "on-tertiary-container": "#003b26",
                        "surface-tint": "#89ceff",
                        "surface-container-highest": "#26364a",
                        "primary": "#89ceff",
                        "on-primary": "#00344d",
                        "on-tertiary-fixed": "#002113",
                        "on-error-container": "#ffdad6",
                        "secondary-fixed": "#dae2fd",
                        "tertiary-fixed-dim": "#4edea3",
                        "error": "#ffb4ab",
                        "secondary": "#bec6e0",
                        "on-tertiary-fixed-variant": "#005236",
                        "surface-container": "#102034",
                        "primary-fixed": "#c9e6ff",
                        "secondary-container": "#3f465c",
                        "tertiary": "#4edea3",
                        "outline": "#88929b",
                        "on-secondary-fixed": "#131b2e",
                        "surface-container-high": "#1b2b3f",
                        "on-primary-container": "#003751",
                        "error-container": "#93000a",
                        "inverse-on-surface": "#213145",
                        "primary-fixed-dim": "#89ceff",
                        "on-primary-fixed-variant": "#004c6e",
                        "on-secondary-fixed-variant": "#3f465c",
                        "tertiary-fixed": "#6ffbbe",
                        "on-surface": "#d3e4fe",
                        "primary-container": "#0ea5e9",
                        "surface": "#031427",
                        "on-tertiary": "#003824",
                        "inverse-primary": "#006591",
                        "surface-container-low": "#0b1c30",
                        "inverse-surface": "#d3e4fe",
                        "on-secondary": "#283044",
                        "on-primary-fixed": "#001e2f",
                        "background": "#031427",
                        "tertiary-container": "#00b17b",
                        "on-error": "#690005",
                        "on-background": "#d3e4fe",
                        "surface-bright": "#2a3a4f",
                        "outline-variant": "#3e4850",
                        "secondary-fixed-dim": "#bec6e0",
                        "surface-variant": "#26364a",
                        "on-surface-variant": "#bec8d2"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "gutter": "24px",
                        "margin": "32px",
                        "container-max": "1440px",
                        "unit": "4px"
                    },
                    "fontFamily": {
                        "display-lg": ["Inter"],
                        "label-sm": ["JetBrains Mono"],
                        "body-md": ["Inter"],
                        "headline-sm": ["Inter"],
                        "headline-md": ["Inter"],
                        "label-md": ["JetBrains Mono"],
                        "body-lg": ["Inter"],
                        "headline-lg": ["Inter"],
                        "body-sm": ["Inter"]
                    },
                    "fontSize": {
                        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                        "label-sm": ["10px", {"lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "500"}],
                        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
                        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
                    }
                },
            },
        };