# Generated by Django 6.0.2 on 2026-02-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_topic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic_questions',
            name='quiz_topic',
        ),
        migrations.DeleteModel(
            name='Question_Answer_Options',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Quiz_Topic',
        ),
        migrations.DeleteModel(
            name='Topic_Questions',
        ),
    ]
